name: clang-format

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-format-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: RafikFarhad/clang-format-github-action@v6
        name: clang-format
        with:
          sources: "src/**/*.hpp,src/**/*.cpp"
          style: "file"
