name: freebsd

on: [ push, pull_request ]

jobs:
  clang:
    # Run actions in a FreeBSD VM on the macos-12 runner
    # https://github.com/actions/runner/issues/385 - for FreeBSD runner support
    # https://github.com/actions/virtual-environments/issues/4060 - for lack of VirtualBox on MacOS 11 runners
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD VM
      uses: vmactions/freebsd-vm@v0
      with:
        mem: 2048
        usesh: true
        prepare: |
          export CPPFLAGS=-isystem/usr/local/include LDFLAGS=-L/usr/local/lib # sndio
          sed -i '' 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
          pkg install -y git #  subprojects/date
          pkg install -y catch evdev-proto gtk-layer-shell gtkmm30 jsoncpp \
            libdbusmenu libevdev libfmt libmpdclient libudev-devd meson \
            pkgconf pulseaudio scdoc sndio spdlog wayland-protocols upower
        run: |
          meson build -Dman-pages=enabled
          ninja -C build
          meson test -C build --no-rebuild --print-errorlogs --suite waybar
